### PR TITLE
Solved issue #91 ,turned off debug mode

### PR DESCRIPTION
**Pull request by JanviRaina**
fix : #91

### CODE REVIEW

**Comment by P0intMaN** [comment]
Great @JanviRaina ,
It would be better if you could address the issue as well. That way, PRs would be more systematic and organized.

**Comment by JanviRaina** [comment]
> Great @JanviRaina , It would be better if you could address the issue as well. That way, PRs would be more systematic and organized.
> 
> Just type **fix : #issueId** in the description

Thanks for this.

**Comment by P0intMaN** [comment]
Now that's better. Alright, I am now gonna merge this.

**Review by P0intMaN — APPROVED** [review]
LGTM!

**Comment by P0intMaN** [comment]
Feel free to hang around, @JanviRaina  and see if you can fix an issue. Would be of great help.

**Comment by JanviRaina** [comment]
> Feel free to hang around, @JanviRaina and see if you can fix an issue. Would be of great help.
> 
> Thanks!

Yup, I will. The website looks quite cool.

**Comment by P0intMaN** [comment]
Thanks and quite buggy too 😅. `zbunker-website` is at its primal stage. Will improve as we gradually progress, fixing one bug at a time.

**Comment by JanviRaina** [comment]
Oh Okay😅

**Pull request merged**
