### PR TITLE
Pull request template is created and tested

### PR DESCRIPTION
**Pull request by TusharSharmaIN**
## Fixes

- The pull request template is created and saved in the .github directory.
- The template is tested with a temporary branch, see link here [here](https://github.com/TusharSharmaIN/zbunker-website/pull/1).

### CODE REVIEW

**Review by P0intMaN — APPROVED** [review]
LGTM!

**Comment by P0intMaN** [comment]
Thank you very much @TusharSharmaIN , highly appreciated. 

By the way, are you participating in the Hacktoberfest?

**Comment by TusharSharmaIN** [comment]
Hey, @P0intMaN thank you for accepting my PR. Yes, I am participating in hactoberfest'2021.

**Comment by TusharSharmaIN** [comment]
please merge this PR, thanks 😁

**Comment by P0intMaN** [comment]
@TusharSharmaIN would like to have you around. Feel free to work on any of the issues you'd like. Would be of great help.

Thanks!

**Pull request merged**
